-- TAO DATABASE
create database QLCHDT

--TAO BANG TAIKHOAN
create table TAIKHOAN (
	TAIKHOAN VARCHAR(50) Primary Key,
	MATKHAU VARCHAR(50),
	CHUCVU VARCHAR(50)
)

-- THEM DU LIEU BANG TAIKHOAN
INSERT INTO TAIKHOAN(TAIKHOAN,MATKHAU,CHUCVU) VALUES ('nguyenmanha4003', '12345678','MANAGER')
INSERT INTO TAIKHOAN(TAIKHOAN,MATKHAU,CHUCVU) VALUES ('nguyenmanha4004', '12345678','STAFF')